name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \
              "blacken-docs>=1.16, <2.0" \
              "docutils>=0.21.1, <1.0.0" \
              "markdown-callouts>=0.3.0, <1.0.0" \
              "markdown-exec[ansi]>=1.7.0, <2.0.0" \
              "mkdocs>=1.5, <2.0" \
              "mkdocs-autorefs>=0.5.0, <1.0.0" \
              "mkdocs-bibtex>=2.11.0, <3.0.0" \
              "mkdocs-coverage>=1.0.0, <2.0.0" \
              "mkdocs-gen-files>=0.5.0, <1.0" \
              "mkdocs-jupyter>=0.24.6, <1.0.0" \
              "mkdocs-literate-nav>=0.6.1, <1.0" \
              "mkdocs-material>=9.4.8, <10.0.0" \
              "mkdocs-material-extensions>=1.3, <2.0" \
              "mkdocs-minify-plugin>=0.7.1, <1.0.0" \
              "mkdocs-redirects>=1.2.1, <2.0.0" \
              "mkdocstrings[python]" \
              "pypandoc>=1.13, <2.0"

      - run: mkdocs gh-deploy --force
